BaseUrl= "http://marcelzanluca.com.br/"
LanguageCode= "pt-BR"
Title= "Marcel Zanluca"
paginate = 10
#DisqusShortname = "YOUR_SHORT_NAME_HERE"
#Copyright = "All rights reserved - 2015"
canonifyurls = true

# TEMA
theme = "casper"

# DIST
publishDir = "../docs"

[params]
  description = "Vivendo e aprendendo"
  metadescription = "Mais importante do que a chegada é a caminhada, e não há caminho sem metamorfose: ela é a ponte que torna possível a nossa travessia até os novos continentes a serem descobertos dentro de nós. (Kamila Behling)"
  cover = "images/cover.jpg"
  author = "Marcel Zanluca"
  authorlocation = "Santa Catarina, Brasil"
  authorwebsite = "http://marcelzanluca.com.br"
  #authorbio= "my bio"
  #logo = "images/logo.png"
  #googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "MarcelLZ"
  #twitterName = "vjeantet"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    #twitter = "your_twitter"