BaseUrl= "https://marcelzanluca.com.br/"
LanguageCode= "pt-BR"
Title= "Marcel Zanluca"
paginate = 5
DisqusShortname = "marcelzanluca"
Copyright = "2018"
canonifyurls = true

# THEME
theme = "casper"

# DIST
publishDir = "public"

[params]
  description = "In a quest for knowledge"
  metadescription = "Mais importante do que a chegada é a caminhada, e não há caminho sem metamorfose. (Kamila Behling)"
  author = "Marcel Zanluca"
  authorlocation = "Santa Catarina, Brasil"
  authorwebsite = "https://marcelzanluca.com.br"
  authorbio= "A simple developer"

  # THEME CUSTOMIZATION
  cover = "images/cover.jpeg"
  #logo = "images/logo.png"
  customCss = []

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = ""

  # SOCIAL MEDIA
  linkedinName = "marcelzanluca"
  twitterName = "marcelzanluca"
  githubName = "MarcelLZ"
  googleAnalyticsUserID = "UA-62214014-1"

  [params.social]
    # facebookName = ""

  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"
